import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import DrawerBar from "./components/Drawer/DrawerBar";
import AuthProvider from "./components/AuthProvider/AuthProvider";
import SnackbarProvider from 'react-simple-snackbar'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>



        <AuthProvider>
          <Navbar />

          <DrawerBar />

          <div className="pt-36">{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
